name: Test Vars
on:
  workflow_dispatch:

jobs:
  build-and-deploy-infrastructure:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@main

    - name: Set variable for DPS Configuration
      run: |
          gh variable set IOT_HUB -bsamsHub
          CONN=$(az iot hub connection-string show  -n samsHub  --default --output tsv)
          gh variable set IOT_HUB_CONNECTION -b$CON
          gh variable set IOT_DEVICE -biot-pareto-device
          gh variable set DPS_NAME -bParetoDeployment
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}

