name: Test Vars
on:
  workflow_dispatch:

jobs:
  build-and-deploy-infrastructure:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@main
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.CLUSTER_SERVICE_PRINCIPAL }}

    - name: Install az cli 
      uses: ./.github/actions/install-az-cli

    - name: Set default subscription
      run: az account set --subscription ${{secrets.SUBSCRIPTION_ID}}

    - name: Set variable for DPS Configuration
      run: |
          gh variable set IOT_HUB -bsamsHub
          gh variable set IOT_DEVICE -biot-pareto-device
          gh variable set DPS_NAME -bParetoDeployment
          CONN=$(az iot hub connection-string show --resource-group $RESOURCE_GROUP --query [0].connectionString -o tsv)
          gh variable set IOT_HUB_CONNECTION -b$CON
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}

